### ISSUE TITLE
Persist data after reboot

### ISSUE THREAD

**Issue by brunohorta82** [xoseperez/eeprom_rotate#1]
Hello, this lib can be used to persist data over reboots, like configuration values?

Thanks for your great job :)

**Comment by arihantdaga** [comment]
@brunohorta82 Try that...
EEPROM is essentially meant for persisting data after reboots.

**Comment by xoseperez** [comment]
@brunohorta82  You can use the built-in EEPROM library to persist data. This library is a wrapper around that one to provide better coverage against write failures.
