### ISSUE TITLE
Mb or MB??

### ISSUE THREAD

**Issue by php4fan** [xoseperez/eeprom_rotate#12]
In https://github.com/xoseperez/eeprom_rotate/blob/master/README.md you use `Mb` a lot.

I would immediately assume you mean `MB` (megabytes), but then it turns out that for whatever reason people sometimes do refer to 512kB flash size boards as "4Mb" with a lowercase b as in "4 megabit" which literally is equal to 512 kBytes.

So now I wonder whether you are actually correctly using Mb meaning megabits, or if you mean MB i.e. mehabytes.

**Comment by xoseperez** [comment]
You are right, it should actually say MiB (https://simple.wikipedia.org/wiki/Mebibyte).
It's fixed now. Thank you!
