### ISSUE TITLE
EEPROMr Begin getting into strange loop

### ISSUE THREAD

**Issue by arihantdaga** [xoseperez/eeprom_rotate#4]
I am using espurna. Recently i started getting this strange error - 
After factory reset also the settings wont vanish. I looked all over in the code and all, but couldn't find something. 
Then i checked into this library's code and added few more debug points and found out this that if magic values in sectors has this sort of pattern then the library will always pick up the last stored values and factory reset wont help. I think we might need to check the logic for .begin method again. 
Below is debug log for better understanding the issue. 

```
// Entering Begin Function
Checking Current Sector : 1019 
Magic value for sector #1019 is 128
Calculated CRC: 0xD769
Stored CRC    : 0xD769
Checking Current Sector : 1018 
Magic value for sector #1018 is 129
Calculated CRC: 0x92AB
Stored CRC    : 0x92AB
Found this sector to be new 1018 
Checking Current Sector : 1017 
Magic value for sector #1017 is 130
Calculated CRC: 0x92AE
Stored CRC    : 0x92AE
Found this sector to be new 1017 
Checking Current Sector : 1016 
Magic value for sector #1016 is 127
Calculated CRC: 0xD76B
Stored CRC    : 0xD76B
Found this sector to be new 1016 
Current sector is #1016
Current magic value is #127


// Entering Commit Function 

We re going to write now 
Current Sector Value : 127 
Writing to sector #1019
Writing magic value #128
Commited

// Entering Commit Function 
We re going to write now 
Current Sector Value : 128 
Writing to sector #1018
Writing magic value #129
Committed

```
From log its clear i have 4 sectors - 1019,1018,1017,1016 
My program always does a commit, after initializing for the first time. And it does another commit after i send restart.  So if the program keep doing 2 commits it'll enter into a loop, where it'll always start with sector 1016 and magic value 127. While everytime its always writing to sector 1018 and 1019....

**Comment by arihantdaga** [comment]
I can do a PR but i am not understanding the use of split in begin method.. ?

**Comment by mcspr** [comment]
Note that https://github.com/xoseperez/eeprom_rotate/commit/2ae2b4f0f479fbdd030579f745639039d99b2ea5#diff-d33d3b52664c216f68a5f7d23c3a17ff had this based on pool size, but changed to fixed value instead.

Funnily enough, I too got this problem just now because of the exact same sector layout.

**Comment by xoseperez** [comment]
Maybe using simple 8-bit math would be simpler, thou.

```
newer = (value - best_value) < 128;
```

**Comment by xoseperez** [comment]
@mcspr Both the 8-bit and your approach return same results. I like better un-obfuscated code so I used your calculation.
